version: '3.3'

volumes: 
    mongoshard1_volume:
    mongoshard2_volume:
    mongoconf_volume:
    mariadb_volume:

services:
    # MONGO DB SERVICES
    # Node storing the first shard
    mongoshard1:
        container_name: mongoshard1
        image: mongo
        command: mongod --shardsvr --replSet "mongors1" --dbpath /data/db --port ${MONGO_SHARD_PORT:-27017}
        restart: on-failure
        expose: 
            - "${MONGO_SHARD_PORT:-27017}"
        environment: 
            TERM: xterm
            TZ: ${TIMEZONE}
        volumes:
            - mongoshard1_volume:/data/db

    # Node storing the second shard
    mongoshard2:
        container_name: mongoshard2
        image: mongo
        command: mongod --shardsvr --replSet "mongors2" --dbpath /data/db --port ${MONGO_SHARD_PORT:-27017}
        restart: on-failure
        expose: 
            - "${MONGO_SHARD_PORT:-27017}"
        environment: 
            TERM: xterm
            TZ: ${TIMEZONE}
        volumes: 
            - mongoshard2_volume:/data/db

    # Node storing the configuration for the cluster
    mongoconf:
        container_name: mongoconf
        depends_on: 
            - mongoshard1
            - mongoshard2
        image: mongo
        command: mongod --configsvr --replSet "mongorsconf" --dbpath /data/db --port ${MONGO_CONFIG_PORT:-27017}
        restart: on-failure
        expose: 
            - "${MONGO_CONFIG_PORT:-27017}"
        environment: 
            TERM: xterm
            TZ: ${TIMEZONE}
        volumes: 
            - mongoconf_volume:/data/db

    # Node acting as the router for the cluster
    mongorouter:
        container_name: mongorouter
        depends_on: 
            - mongoconf
        image: mongo
        command: mongos --configdb mongorsconf/mongoconf:${MONGO_CONFIG_PORT:-27017} --port ${MONGO_ROUTER_PORT:-27017} --bind_ip_all
        restart: on-failure
        expose: 
            - "${MONGO_ROUTER_PORT:-27017}"
        ports: 
            - ${MONGO_ROUTER_PORT:-27017}:${MONGO_ROUTER_PORT:-27017}
        environment: 
            TERM: xterm
            TZ: ${TIMEZONE}

    mongo-express:
        container_name: mongoexpress
        image: mongo-express
        restart: on-failure
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: "mongorouter"
            ME_CONFIG_MONGODB_PORT: ${MONGO_ROUTER_PORT:-27017}
            
    # MARIA DB SERVICES
    # MariaDB container
    mariadb:
        container_name: mariadb
        image: mariadb
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASS:-rootpass}
        ports:
            - ${MARIADB_PORT:-3306}:${MARIADB_PORT:-3306}
        volumes:
            - mariadb_volume:/var/lib/mysql

    # MISCELLANEOUS SERVICES
    # Adminer (phpMyAdmin alternative) container
    adminer:
        container_name: adminer
        image: adminer
        restart: on-failure
        ports:
            - ${ADMINER_PORT:-8080}:${ADMINER_PORT:-8080}